version: "3.8"

services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USERNAME=username
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=simple_shop
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

#  app:
#    depends_on:
#      - mysqldb
#    build: ./path_to_your_project
#    restart: on-failure
#    ports:
#      - 8080:8080
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/database_name?useSSL=false",
#        "spring.datasource.username" : "root",
#        "spring.datasource.password" : "root_password",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true

volumes:
  db:
