version: "3.8"

services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=simple_shop
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
